#!/usr/bin/perl

use strict;
use warnings;

use Parse::RecDescent;
use Data::Dumper;

require 'generate_node.pl';
require 'generate_index.pl';
require 'generate_database.pl';


my $name = $ARGV[0];
my $interface = $ARGV[1];
my $implementation = $ARGV[2];

our %node_types = ();
our %database_types = ();
our %index_types = ();
our $int = "";
our $impl = "";

$Parse::RecDescent::skip = '(\s|;)*';

my $grammar = q{
  { my @c = (); my %c = () }

  root: (node_type | index_type | database_type | int | impl | comment)(s?) 
 
  comment: /#[^\\n]*/
  int: 'Interface' block { $::int = $::int . $item[2] }
  impl: 'Implementation' block { $::impl = $::impl . $item[2] }

  node_type: 'NodeType' name '{' node_attribute(s?) '}'
    { $::node_types{$item{name}} = [ @c ]; @c = () }
  node_attribute: 'Attribute' name ':' type
    { push @c, [ $item{name}, $item{type} ] }

  database_type: 'DatabaseType' name '(' identifier ')' '{' (node|index)(s?) '}'
    { $c{version} = $item{identifier};
      $::database_types{$item{name}} = { %c }; %c = () }
  node:  'NodeType'  name 
    { push @{$c{node_types}}, $item{name} }
  index: 'Index' name 'for' identifier ':' type 
    { push @{$c{index_types}}, [ $item{name}, $item{type}, $item{identifier} ] }

  index_type: 'IndexType' name ':' c_type '{' index_i index_d index_u index_e(S?) '}'
    { $c{type} = $item{c_type}; $::index_types{$item{name}} = { %c }; %c = () }
  index_i: 'Init' 

  block: /@\\s*([^@]*)@/ { $1 }
  name: identifier   { $item[1] }
  type: identifier   { $item[1] }
  c_type: /(union|struct)\\s*{[^\}]*}|(\\w+\\s*\\**)+/ { $item[1] }
  identifier: /\\w+/ { $item[1] }
};

my $parser = new Parse::RecDescent($grammar) or die "Error\n";
my @input = <STDIN>;
my $input = join(" ", @input);
$parser->root($input);

# print Dumper(\%node_types);
# print Dumper(\%database_types);
# print Dumper(\%index_types);

# print Dumper(\@include);



if ($interface) {
  print <<EOF;
#ifndef __GENERATED__${name}__INTERFACE__
#define __GENERATED__${name}__INTERFACE__

/*
 * This file is generated by generate.pl
 * Don't edit this file
 */

$int

EOF

  node_interface(\%node_types);
  index_interface(\%index_types);
  database_interface(\%database_types);

  print "\n#endif\n\n";
}


if ($implementation) { 
  print <<EOF;
/*
 * This file is generated by generate.pl
 * Don't edit this file
 */

$impl

EOF

  node_implementation(\%node_types);
  index_implementation(\%index_types);
  database_implementation(\%database_types);
}


